name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.0"

      - name: Arrancar LocalStack
        run: |
          docker run -d \
            --name localstack \
            -p 4566:4566 \
            -e SERVICES=s3,ec2 \
            localstack/localstack:3.0
          sleep 15

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
